package com.pusulait.airsqreen.domain.enums;

/**
  */
public enum ErrorType {
     USER_NOT_EXIST
    ,USER_BY_ID
    ,GET_ALL_COUNTRIES
    ,GET_COUNTRY
    ,CREATE_COUNTRY
    ,UPDATE_COUNTRY
    ,DELETE_COUNTRY
    ,GET_ALL_CITIES
    ,GET_CITY
    ,GET_CITY_BY_COUNTRY_ID
    ,CREATE_CITY
    ,UPDATE_CITY
    ,DELETE_CITY
    ,GET_ALL_USERS
    ,GET_USER
    ,GET_USER_ROLE
    ,GET_USER_ROLES
    ,ALL_USER_SEARCH
    ,REGISTER
    ,USER_EXIST

    ,GET_PROVINCE
    ,CREATE_PROVINCE
    ,UPDATE_PROVINCE
    ,DELETE_PROVINCE
    ,GET_ALL_PROVINCES

    ,GET_CARRIER
    ,CREATE_CARRIER
    ,UPDATE_CARRIER
    ,DELETE_CARRIER
    ,GET_ALL_CARRIERS

    ,GET_FLIGHT_DATA_PROVIDER
    ,CREATE_FLIGHT_DATA_PROVIDER
    ,UPDATE_FLIGHT_DATA_PROVIDER
    ,DELETE_FLIGHT_DATA_PROVIDER
    ,GET_ALL_FLIGHT_DATA_PROVIDER

    ,GET_FLIGHT_AGENCY
    ,CREATE_FLIGHT_AGENCY
    ,UPDATE_FLIGHT_AGENCY
    ,DELETE_FLIGHT_AGENCY
    ,GET_ALL_FLIGHT_AGENCY

    ,GET_DESTINATION
    ,CREATE_DESTINATION
    ,UPDATE_DESTINATION
    ,DELETE_DESTINATION
    ,GET_ALL_DESTINATION

    ,GET_CREDIT_CART_PROVIDER
    ,CREATE_CREDIT_CART_PROVIDER
    ,UPDATE_CREDIT_CART_PROVIDER
    ,DELETE_CREDIT_CART_PROVIDER
    ,GET_ALL_CREDIT_CART_PROVIDER

    ,GET_RIGHT
    ,GET_ALL_RIGHT

    ,GET_ROLE_RIGHT
    ,GET_ALL_ROLE_RIGHT,
    GET_ALL_ROLE,
    GET_ROLE


    ,GET_ALL_SYSTEM_CONFIGURATIONS
    ,GET_SYSTEM_CONFIGURATION
    ,CREATE_SYSTEM_CONFIGURATION
    ,UPDATE_SYSTEM_CONFIGURATION
    ,DELETE_SYSTEM_CONFIGURATION


    ,GET_ALL_CURRENCIES
    ,GET_CURRENCY
    ,CREATE_CURRENCY
    ,UPDATE_CURRENCY
    ,DELETE_CURRENCY


    ,GET_ALL_CURRENY_RATES
    ,GET_CURRENCY_RATE
    ,CREATE_CURRENCY_RATE
    ,UPDATE_CURRENCY_RATE
    ,DELETE_CURRENCY_RATE


    ,GET_ALL_LUGGAGE_CANCELLATIONS
    ,GET_LUGGAGE_CANCELLATION
    ,CREATE_LUGGAGE_CANCELLATION
    ,UPDATE_LUGGAGE_CANCELLATION
    ,DELETE_LUGGAGE_CANCELLATION
}
