package com.pusulait.airsqreen.domain.enums;

/**
  */
public enum ErrorType {

    GET_ALL_RIGHT,
    GET_ROLE_RIGHT,
    GET_ALL_ROLE,
    GET_ROLE,
    GET_USER_ROLES,
    GET_ALL_USERS,
    ALL_USER_SEARCH,
    GET_USER,
    REGISTER,
    CREATE_DEVICE,
    GET_ALL_DEVICES,
    CREATE_PLATFORM_USER,
    GET_ALL_PLATFORM_USERS,
    GET_DEVICE_DEVICE_CONSTRAINT_LIST,
    GET_ALL_CAMPAINGS,
    FIND_SECTION,
    SSPVIEWCOUNTLOGSEARCH
}
